/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterviewConfigurationFrame.java
 *
 * Created on 03.11.2008, 15:18:12
 */

package gui.admin;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * 
 * 
 */
public class InterviewConfigurationFrame extends javax.swing.JFrame {

	/** Creates new form InterviewConfigurationFrame */
	public InterviewConfigurationFrame() {
		initComponents();
		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		int top = (screenSize.height - this.getHeight()) / 2;
		int left = (screenSize.width - this.getWidth()) / 2;
		setLocation(left, top);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        editEgoAttrButton = new javax.swing.JButton();
        egoMoveableBox = new javax.swing.JCheckBox();
        egoResizableBox = new javax.swing.JCheckBox();
        egoDisableBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        egoAttributeTable = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        deleteEgoAttrButton = new javax.swing.JButton();
        newEgoAttrButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        indirectQuestionField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        maxNumberAlteriSpinner = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        nonRelationalTable = new javax.swing.JTable();
        newNonRelationalButton = new javax.swing.JButton();
        editNonRelationalButton = new javax.swing.JButton();
        deleteNonRelationalButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        timeSequenceList = new javax.swing.JList();
        editTextBoxButton = new javax.swing.JButton();
        deleteTextBoxButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        newTextBoxButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        startInterviewButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configure Interview");
        setMinimumSize(new java.awt.Dimension(600, 400));

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(0, 0));

        editEgoAttrButton.setText("Edit");
        editEgoAttrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEgoAttrButtonActionPerformed(evt);
            }
        });

        egoMoveableBox.setText("Ego is moveable");

        egoResizableBox.setText("Size of ego is changeable");

        egoDisableBox.setText("Disable ego");

        jLabel1.setText("If you disable ego the interview will only contain alteri.");

        egoAttributeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Label", "Question", "Answer Type"
            }
        ));
        jScrollPane10.setViewportView(egoAttributeTable);

        jLabel20.setText("Ego's attributes:");

        deleteEgoAttrButton.setText("Delete");

        newEgoAttrButton.setText("New");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addComponent(egoResizableBox)
                    .addComponent(egoDisableBox)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addComponent(egoMoveableBox)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newEgoAttrButton)
                        .addGap(18, 18, 18)
                        .addComponent(editEgoAttrButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteEgoAttrButton))
                    .addComponent(jLabel20))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(egoDisableBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(egoMoveableBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(egoResizableBox)
                .addGap(33, 33, 33)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newEgoAttrButton)
                    .addComponent(editEgoAttrButton)
                    .addComponent(deleteEgoAttrButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ego", jPanel1);

        jLabel3.setText("General question for name list");

        jLabel16.setText("Max. Number of Alteri");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indirectQuestionField, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(maxNumberAlteriSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indirectQuestionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxNumberAlteriSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(514, 514, 514))
        );

        jTabbedPane1.addTab("Name Generator", jPanel3);

        nonRelationalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Label", "Question", "Answer Type", "Point of measurement"
            }
        ));
        jScrollPane9.setViewportView(nonRelationalTable);
        nonRelationalTable.getColumnModel().getColumn(3).setHeaderValue("Point of measurement");

        newNonRelationalButton.setText("New");

        editNonRelationalButton.setText("Edit");
        editNonRelationalButton.setEnabled(false);

        deleteNonRelationalButton.setText("Delete");
        deleteNonRelationalButton.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(newNonRelationalButton)
                        .addGap(18, 18, 18)
                        .addComponent(editNonRelationalButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteNonRelationalButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newNonRelationalButton)
                    .addComponent(editNonRelationalButton)
                    .addComponent(deleteNonRelationalButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Name Interpreter", jPanel2);

        timeSequenceList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(timeSequenceList);

        editTextBoxButton.setText("Edit");

        deleteTextBoxButton.setText("Delete");
        deleteTextBoxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTextBoxButtonActionPerformed(evt);
            }
        });

        downButton.setText("Down");
        downButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });

        upButton.setText("Up");

        newTextBoxButton.setText("New text wizard");
        newTextBoxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTextBoxButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newTextBoxButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(editTextBoxButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(deleteTextBoxButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(downButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(upButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(newTextBoxButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editTextBoxButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteTextBoxButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                        .addComponent(upButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downButton)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Time Sequence", jPanel7);

        saveButton.setText("Save");

        startInterviewButton.setText("Start Interview");

        loadButton.setText("Load");

        exitButton.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startInterviewButton)
                        .addGap(18, 18, 18)
                        .addComponent(exitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton)
                    .addComponent(saveButton)
                    .addComponent(startInterviewButton)
                    .addComponent(exitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void configureEgoNewButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_configureEgoNewButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_configureEgoNewButtonActionPerformed

	private void editEgoAttrButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editEgoAttrButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_editEgoAttrButtonActionPerformed

	private void newTextBoxButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newTextBoxButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_newTextBoxButtonActionPerformed

	private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_downButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_downButtonActionPerformed

	private void deleteTextBoxButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteTextBoxButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_deleteTextBoxButtonActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new InterviewConfigurationFrame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton deleteEgoAttrButton;
    protected javax.swing.JButton deleteNonRelationalButton;
    protected javax.swing.JButton deleteTextBoxButton;
    protected javax.swing.JButton downButton;
    protected javax.swing.JButton editEgoAttrButton;
    protected javax.swing.JButton editNonRelationalButton;
    protected javax.swing.JButton editTextBoxButton;
    protected javax.swing.JTable egoAttributeTable;
    protected javax.swing.JCheckBox egoDisableBox;
    protected javax.swing.JCheckBox egoMoveableBox;
    protected javax.swing.JCheckBox egoResizableBox;
    protected javax.swing.JButton exitButton;
    protected javax.swing.JTextField indirectQuestionField;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel16;
    protected javax.swing.JLabel jLabel20;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JPanel jPanel3;
    protected javax.swing.JPanel jPanel7;
    protected javax.swing.JScrollPane jScrollPane10;
    protected javax.swing.JScrollPane jScrollPane4;
    protected javax.swing.JScrollPane jScrollPane9;
    protected javax.swing.JTabbedPane jTabbedPane1;
    protected javax.swing.JButton loadButton;
    protected javax.swing.JSpinner maxNumberAlteriSpinner;
    protected javax.swing.JButton newEgoAttrButton;
    protected javax.swing.JButton newNonRelationalButton;
    protected javax.swing.JButton newTextBoxButton;
    protected javax.swing.JTable nonRelationalTable;
    protected javax.swing.JButton saveButton;
    protected javax.swing.JButton startInterviewButton;
    protected javax.swing.JList timeSequenceList;
    protected javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables

}
