/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminDialog.java
 *
 * Created on 30.10.2008, 23:21:25
 */

package gui.admin;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * 
 */
public class VariableDefinitonDialog extends javax.swing.JDialog {

    /** Creates new form AdminDialog */
    public VariableDefinitonDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		int top = (screenSize.height - this.getHeight()) / 2;
		int left = (screenSize.width - this.getWidth()) / 2;
		setLocation(left, top);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configure Interview Environment");
        setResizable(false);

        jPanel2.setLayout(new java.awt.BorderLayout());

        dialogXHeader.setTitle("Configure attributes");
        jPanel2.add(dialogXHeader, java.awt.BorderLayout.PAGE_START);

        jXPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jXPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Question"));
        jPanel4.setFont(jPanel4.getFont().deriveFont((float)10));

        jXLabel1.setText("Related question ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(questionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Answer type"));
        jPanel7.setFont(jPanel7.getFont().deriveFont((float)10));

        buttonGroup1.add(numericalAnswerButton);
        numericalAnswerButton.setText("Numerical");
        numericalAnswerButton.setEnabled(false);

        jLabel1.setDisplayedMnemonic('u');
        jLabel1.setLabelFor(unitNameTextField);
        jLabel1.setText("Unit");
        jLabel1.setToolTipText("The name of the unit associated with the numerical value, e.g. currency name. Can also be empty.");

        unitNameTextField.setToolTipText("The name of the unit associated with the numerical value, e.g. currency name. Can also be empty.");
        unitNameTextField.setEnabled(false);

        jLabel2.setText("Minimal value:");

        jLabel3.setText("Maximal value:");

        minimalValueSpinner.setEnabled(false);

        maximalValueSpinner.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unitNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(maximalValueSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(minimalValueSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                .addGap(129, 129, 129))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(unitNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(minimalValueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maximalValueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        buttonGroup1.add(freeFormAnswerButton);
        freeFormAnswerButton.setText("Text");
        freeFormAnswerButton.setEnabled(false);
        freeFormAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeFormAnswerButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(predefinedAnswersList);

        predefinedAnswerNewButton.setText("New...");

        predefinedAnswerEditButton.setText("Edit...");

        predefinedAnswerDeleteButton.setText("Delete");

        allowMultipleSelectionsBox.setText("Allow \"Pick all that apply\"");
        allowMultipleSelectionsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allowMultipleSelectionsBoxActionPerformed(evt);
            }
        });

        allowFreeAnswersBox.setText("Allow free answers");
        allowFreeAnswersBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allowFreeAnswersBoxActionPerformed(evt);
            }
        });

        allowNoAnswerBox.setSelected(true);
        allowNoAnswerBox.setText("Allow \"No Answer\"");

        allowDontKnowBox.setSelected(true);
        allowDontKnowBox.setText("Allow \"Don't know\"");

        jLabel7.setText("Categorical");

        jScrollPane1.setViewportView(visualMappingList);

        visualMappingEdit.setText("Edit");

        jLabel8.setText("Attribute Visualization");

        visualMappingSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Actor Type", "Actor Size", "Relation Type", "Sector", "Circle" }));
        visualMappingSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualMappingSelectionActionPerformed(evt);
            }
        });

        matrix.setText("Matrix");
        matrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrixActionPerformed(evt);
            }
        });

        askOnBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Start of interview", "Adding to network", "End of interview" }));

        jLabel4.setText("Ask on");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(allowNoAnswerBox)
                    .addComponent(allowDontKnowBox)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(freeFormAnswerButton)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(numericalAnswerButton)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(allowFreeAnswersBox)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(predefinedAnswerNewButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(predefinedAnswerEditButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(predefinedAnswerDeleteButton))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(allowMultipleSelectionsBox)
                                .addGap(57, 57, 57)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(visualMappingSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(matrix)
                                        .addGap(18, 18, 18)
                                        .addComponent(visualMappingEdit)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(askOnBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(visualMappingSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allowMultipleSelectionsBox)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(predefinedAnswerNewButton)
                    .addComponent(predefinedAnswerEditButton)
                    .addComponent(predefinedAnswerDeleteButton)
                    .addComponent(visualMappingEdit)
                    .addComponent(matrix))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allowFreeAnswersBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(freeFormAnswerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(numericalAnswerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(allowNoAnswerBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(allowDontKnowBox)
                        .addGap(21, 21, 21))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(askOnBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        okButton.setText("OK");

        cancelButton.setText("Cancel");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Attribute"));

        jLabel5.setText("Name of attribute");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(attributesNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(attributesNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jXPanel1Layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        jPanel2.add(jXPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allowFreeAnswersBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allowFreeAnswersBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_allowFreeAnswersBoxActionPerformed

    private void freeFormAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeFormAnswerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freeFormAnswerButtonActionPerformed

    private void allowMultipleSelectionsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allowMultipleSelectionsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allowMultipleSelectionsBoxActionPerformed

    private void visualMappingSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualMappingSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visualMappingSelectionActionPerformed

    private void matrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrixActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_matrixActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VariableDefinitonDialog dialog = new VariableDefinitonDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected final javax.swing.JCheckBox allowDontKnowBox = new javax.swing.JCheckBox();
    protected final javax.swing.JCheckBox allowFreeAnswersBox = new javax.swing.JCheckBox();
    protected final javax.swing.JCheckBox allowMultipleSelectionsBox = new javax.swing.JCheckBox();
    protected final javax.swing.JCheckBox allowNoAnswerBox = new javax.swing.JCheckBox();
    protected final javax.swing.JComboBox askOnBox = new javax.swing.JComboBox();
    protected final javax.swing.JTextField attributesNameField = new javax.swing.JTextField();
    protected final javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
    protected final javax.swing.JButton cancelButton = new javax.swing.JButton();
    protected final org.jdesktop.swingx.JXHeader dialogXHeader = new org.jdesktop.swingx.JXHeader();
    protected final javax.swing.JRadioButton freeFormAnswerButton = new javax.swing.JRadioButton();
    protected final javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    protected final javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
    protected final javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
    protected final javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
    protected final javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
    protected final javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
    protected final javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
    protected final javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
    protected final javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
    protected final javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
    protected final javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
    protected final javax.swing.JPanel jPanel7 = new javax.swing.JPanel();
    protected final javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    protected final javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
    protected final org.jdesktop.swingx.JXLabel jXLabel1 = new org.jdesktop.swingx.JXLabel();
    protected final org.jdesktop.swingx.JXPanel jXPanel1 = new org.jdesktop.swingx.JXPanel();
    protected final javax.swing.JCheckBox matrix = new javax.swing.JCheckBox();
    protected final javax.swing.JSpinner maximalValueSpinner = new javax.swing.JSpinner();
    protected final javax.swing.JSpinner minimalValueSpinner = new javax.swing.JSpinner();
    protected final javax.swing.JRadioButton numericalAnswerButton = new javax.swing.JRadioButton();
    protected final javax.swing.JButton okButton = new javax.swing.JButton();
    protected final javax.swing.JButton predefinedAnswerDeleteButton = new javax.swing.JButton();
    protected final javax.swing.JButton predefinedAnswerEditButton = new javax.swing.JButton();
    protected final javax.swing.JButton predefinedAnswerNewButton = new javax.swing.JButton();
    protected final javax.swing.JList predefinedAnswersList = new javax.swing.JList();
    protected final javax.swing.JTextField questionTextField = new javax.swing.JTextField();
    protected final javax.swing.JTextField unitNameTextField = new javax.swing.JTextField();
    protected final javax.swing.JButton visualMappingEdit = new javax.swing.JButton();
    protected final javax.swing.JList visualMappingList = new javax.swing.JList();
    protected final javax.swing.JComboBox visualMappingSelection = new javax.swing.JComboBox();
    // End of variables declaration//GEN-END:variables

}
